const huntingAnimals = [
  {
    img: "https://idfg.idaho.gov/sites/default/files/styles/max-height-full-width/public/media/white-tailed_deer_buck.jpg?itok=A8ERLqHi",
    name: "Whitetail deer",
    huntingkind: "big game",
    season: ["may", "june", "july", "august", "september"],
    zone: ["north america"],
    type: "deer",
    usdPrice: 300,
  },
  {
    img: "https://www.collinsdictionary.com/images/full/wapiti_383586835.jpg",
    name: "Wapiti",
    huntingkind: "big game",
    season: ["may", "june", "july", "august", "september"],
    zone: ["USA", "canada"],
    type: "deer",
    usdPrice: 500,
  },
  {
    img: "https://assets.simpleviewinc.com/simpleview/image/upload/c_limit,h_1200,q_75,w_1200/v1/clients/anchorage-redesign/12589676HighRes_5347e631-39c0-418a-b69d-b6b6e1bbff6f.jpg",
    name: "Moose",
    huntingkind: "big game",
    season: ["november", "december", "january", "february"],
    zone: ["alaska", "canada"],
    type: "deer",
    usdPrice: 650,
  },
  {
    img: "https://images.theconversation.com/files/349961/original/file-20200728-29-6nb8o5.jpg?ixlib=rb-1.1.0&rect=46%2C279%2C5178%2C2589&q=45&auto=format&w=1356&h=668&fit=crop",
    name: "Mountain Goat",
    huntingkind: "big game",
    season: ["december"],
    zone: ["alaska"],
    type: "goat",
    usdPrice: 250,
  },
  {
    img: "https://www.realtree.com/sites/default/files/content/images/open-graph/cimagesonthewildside-deer-coues.jpg",
    name: "Coues whitetail deer",
    huntingkind: "big game",
    season: ["july"],
    zone: ["USA"],
    type: "deer",
    usdPrice: 225,
  },
  {
    img: "https://thumbs.dreamstime.com/b/puntal-del-gobbler-1705063.jpg",
    name: "Guajolote",
    huntingkind: "small game",
    season: ["august", "september", "october"],
    zone: ["mexico"],
    type: "turkey",
    usdPrice: 200,
  },
  {
    img: "http://www.falstaff.com/fileadmin/_processed_/a/b/csm_wild-boar_bd62d149a1.jpg",
    name: "Wild boar",
    huntingkind: "big game",
    season: ["april"],
    zone: ["mexico", "USA"],
    type: "pig",
    usdPrice: 315,
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/commons/a/a7/Mule_buck_elk_creek_m_myatt_%285489214303%29.jpg",
    name: "Mule deer",
    huntingkind: "big game",
    season: ["april"],
    zone: ["USA"],
    type: "deer",
    usdPrice: 650,
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/commons/0/08/01_Schwarzb%C3%A4r.jpg",
    name: "Black bear",
    huntingkind: "big game",
    season: ["november"],
    zone: ["USA", "canada"],
    type: "bear",
    usdPrice: 850,
  },
  {
    img: "https://www.greenbirding.ca/wp-content/uploads/2020/03/2020030122.jpg",
    name: "Winter cottontail rabbit",
    huntingkind: "small game",
    season: ["november"],
    zone: ["USA", "canada"],
    type: "rabbit",
    usdPrice: 25,
  },
  {
    img: "https://media.npr.org/assets/img/2018/09/14/gettyimages-1032854500_custom-7f22f7cd65e8bfb64649ca53f807c96a88a12f37-s1100-c50.jpg",
    name: "Raccoon",
    huntingkind: "small game",
    season: ["november"],
    zone: ["USA", "canada"],
    type: "rabbit",
    usdPrice: 25,
  },
  {
    img: "https://upload.wikimedia.org/wikipedia/commons/1/15/EasternGraySquirrel_GAm.jpg",
    name: "Squirrel",
    huntingkind: "small game",
    season: ["november"],
    zone: ["USA", "canada"],
    type: "rabbit",
    usdPrice: 25,
  },
  {
    img: "https://widnr.widen.net/content/nmd7fqwkdf/jpeg/Mallard-duck-%28Anas-platyrhynchos%29-976067906_3216x2136.jpeg?position=c&color=cccccc&quality=80&u=jxqttz",
    name: "Green head duck",
    huntingkind: "small game",
    season: ["november"],
    zone: ["USA", "canada"],
    type: "duck",
    usdPrice: 40,
  },
  {
    img: "https://www.barrameda.com.ar/wp-content/uploads/2019/12/pecari.jpg",
    name: "Pecari",
    huntingkind: "big game",
    season: ["september"],
    zone: ["north america"],
    type: "pig",
    usdPrice: 275,
  },
];

module.exports = huntingAnimals;
